version: "3.7"

services:
  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: taskit
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    ports: 
      - "5432:5432"
    networks: 
      - taskit

  redis:
    build: "./backend/database/redis"
    restart: always
    ports:
      - "6379:6379"
    networks: 
      - taskit

  backend:
    build: "./backend"
    restart: always
    ports:
      - "3333:3333"
    depends_on: 
      - postgres
      - redis
    networks: 
      - taskit
    command: ["./wait-for-it.sh", "postgres:5432", "--", "adonis", "migration:run", "--", "yarn", "start"]

  frontend:
    build: "./frontend"
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - backend
    networks: 
      - taskit
networks: 
  taskit: 